
openapi: 3.0.0
info:
  title: Rebase Schemas
  version: 1.0.0
servers:
  - url: https://w3id.org/rebase/openapi

paths:
  /schemas/common/GitHubVerification.yml:
    get:
      tags:
      - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './schemas/common/GitHubVerification.yml'
    

  /schemas/common/GitHubVerificationMessage.yml:
    get:
      tags:
      - Common
      responses:
        '200':
          content:
            application/yml:
              schema:
                $ref: './schemas/common/GitHubVerificationMessage.yml'
    